### ISSUE TITLE
installed but didn't show the open after open files

### ISSUE THREAD

**Issue by edyywang** [postcasio/tree-view-open-files#28]
Already installed the plug-in and used to show the open file pane, but somehow it just hidden and never show. Not sure how to open it

**Comment by BoweFrankema** [comment]
It seems the extension broke during an Atom upgrade.. sadly it has disappeared for me as well

**Comment by nlefebvre** [comment]
This pull request solves the problem: https://github.com/postcasio/tree-view-open-files/pull/25

I wasn't sure how to apply this quickly, so I cloned the repo into my .atom/packages/ folder (replaced what was there), changed atom-utils to the updated version in package.json, ran npm install and reopened Atom, which works.

But the real solution is for postcasio to accept the pull request and release again.

**Comment by dbkaplun** [comment]
+1 doesn't work on latest Atom.

**Comment by mescribe0** [comment]
+1 doesn't work on latest Atom 1.1.0. I just updated.

**Comment by marshallbu** [comment]
Looks as if @postcasio has had no Git activity in over 5 months, maybe we should create a new plugin?

**Comment by postcasio** [comment]
Sorry all. 0.3.0 is now out and it should be working again.

**Comment by nlefebvre** [comment]
Thanks for the fix :)

**Comment by rafaelrp** [comment]
Doesn't work here on latest Atom 1.17.0, any solution? Thanks
