### ISSUE TITLE
Enhancement request: Option to use a fixed height

### ISSUE THREAD

**Issue by eksortso** [postcasio/tree-view-open-files#48]
This is a great package, but I have a request for an enhancement, based on my typical usage.

I sometimes double-click entries in the tree view, so that files are permanently opened, not just previewed. But if I open a document for the first time using a double-click, the open-files list expands (if it's below Max Height), which causes my second click to open the wrong document in the tree view.

A checkbox setting that forces the open-file list to its Max Height regardless of the number of open files would be very useful in this regard.

What do you think?

**Comment by sergiu-gordienco** [comment]
@eksortso  **Solved**, fixed for atom 1.18.0 https://github.com/sergiu-gordienco/tree-view-open-files

on atom is tree-view-open-files-updated

`apm install tree-view-open-files-updated`

https://atom.io/packages/tree-view-open-files-updated

**Comment by eksortso** [comment]
@sergiu-gordienco I tried this. It isn't working at all. It doesn't display the open files list. And when I toggle the Tree View, I get an error on tree-view-open-files-updated\lib\tree-view-open-files.coffee:27, "ref.is is not a function". I'd create an issue, but the link that Atom gives me on the bug popup sends me to a 404 page.

**Comment by eksortso** [comment]
I'll go ahead and close this ticket. It's been years since I used Atom, and you've claimed the problem's solved a long time ago.
