### ISSUE TITLE
Indicate when files in `tree-view-open-files` contain unsaved changes

### ISSUE THREAD

**Issue by timohofmeijer** [postcasio/tree-view-open-files#7]

**Comment by papermoon1978** [comment]
Looks like I'm not the only one missing this. ;-) Can you please check my fork if it also fits your needs? I'll then of course fill a pull request later on.

**Comment by timohofmeijer** [comment]
Sweet, I'll do so as soon as I have time!

**Comment by timohofmeijer** [comment]
Did't look at your fork yet, but I did notice version 0.2.3 implements this feature, which is awesome! No matter how this ball rolled, great work @papermoon1978 & @postcasio.

**Comment by postcasio** [comment]
Whoops, forgot about this issue :) I noticed the fork and it gave me a push to implement it. Hope it works well for you.

**Comment by papermoon1978** [comment]
Works really fine. Thank you very much.:-)
